// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalulatorClient is the client API for Calulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalulatorClient interface {
	// grpc一共有四种类型的服务，简单模式、服务端流、客户端流、双向流。这是第一种。
	Calculate(ctx context.Context, in *CalulatorRequest, opts ...grpc.CallOption) (*CalulatorResponse, error)
}

type calulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalulatorClient(cc grpc.ClientConnInterface) CalulatorClient {
	return &calulatorClient{cc}
}

func (c *calulatorClient) Calculate(ctx context.Context, in *CalulatorRequest, opts ...grpc.CallOption) (*CalulatorResponse, error) {
	out := new(CalulatorResponse)
	err := c.cc.Invoke(ctx, "/Calulator/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalulatorServer is the server API for Calulator service.
// All implementations must embed UnimplementedCalulatorServer
// for forward compatibility
type CalulatorServer interface {
	// grpc一共有四种类型的服务，简单模式、服务端流、客户端流、双向流。这是第一种。
	Calculate(context.Context, *CalulatorRequest) (*CalulatorResponse, error)
	mustEmbedUnimplementedCalulatorServer()
}

// UnimplementedCalulatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalulatorServer struct {
}

func (UnimplementedCalulatorServer) Calculate(context.Context, *CalulatorRequest) (*CalulatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedCalulatorServer) mustEmbedUnimplementedCalulatorServer() {}

// UnsafeCalulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalulatorServer will
// result in compilation errors.
type UnsafeCalulatorServer interface {
	mustEmbedUnimplementedCalulatorServer()
}

func RegisterCalulatorServer(s grpc.ServiceRegistrar, srv CalulatorServer) {
	s.RegisterService(&Calulator_ServiceDesc, srv)
}

func _Calulator_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalulatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalulatorServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calulator/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalulatorServer).Calculate(ctx, req.(*CalulatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Calulator_ServiceDesc is the grpc.ServiceDesc for Calulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Calulator",
	HandlerType: (*CalulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Calulator_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "add.proto",
}
